"""Update unique constraint to exclude deleted files

Revision ID: 1e29512324da
Revises: f7e384cc3dae
Create Date: 2025-09-19 16:10:47.007393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e29512324da'
down_revision = 'f7e384cc3dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_file_per_repo'), 'repository_files', type_='unique')
    op.create_index('unique_file_per_repo', 'repository_files', ['repository_id', 'file_path'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_file_per_repo', table_name='repository_files', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('unique_file_per_repo'), 'repository_files', ['repository_id', 'file_path'])
    # ### end Alembic commands ###