"""remove_redundant_fields_from_model_services

Revision ID: 33e243eebe56
Revises: 984258eaed7e
Create Date: 2025-08-06 02:59:45.323171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e243eebe56'
down_revision = '984258eaed7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_services', 'gradio_port',
               existing_type=sa.INTEGER(),
               comment='服务端口（主机端口和容器端口统一）',
               existing_comment='主机端口',
               existing_nullable=True)
    op.drop_index(op.f('idx_model_services_model_id'), table_name='model_services')
    op.create_index('idx_model_services_image', 'model_services', ['image_id'], unique=False)
    op.drop_column('model_services', 'container_name')
    op.drop_column('model_services', 'model_id')
    op.drop_column('model_services', 'container_port')
    op.drop_column('model_services', 'docker_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_services', sa.Column('docker_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Docker镜像名称'))
    op.add_column('model_services', sa.Column('container_port', sa.INTEGER(), autoincrement=False, nullable=True, comment='容器内部端口'))
    op.add_column('model_services', sa.Column('model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='模型标识符'))
    op.add_column('model_services', sa.Column('container_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='容器名称'))
    op.drop_index('idx_model_services_image', table_name='model_services')
    op.create_index(op.f('idx_model_services_model_id'), 'model_services', ['model_id'], unique=False)
    op.alter_column('model_services', 'gradio_port',
               existing_type=sa.INTEGER(),
               comment='主机端口',
               existing_comment='服务端口（主机端口和容器端口统一）',
               existing_nullable=True)
    # ### end Alembic commands ###