"""Add service retry and priority fields

Revision ID: 3a612e7ae8f0
Revises: 069954ae4d9a
Create Date: 2025-07-29 01:49:09.374505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a612e7ae8f0'
down_revision = '069954ae4d9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_services', sa.Column('priority', sa.Integer(), nullable=True, comment='启动优先级，数值越小优先级越高'))
    op.add_column('model_services', sa.Column('auto_start_retry_count', sa.Integer(), nullable=True, comment='自动启动重试次数'))
    op.add_column('model_services', sa.Column('last_failure_reason', sa.Text(), nullable=True, comment='最后一次失败原因'))
    op.add_column('model_services', sa.Column('failure_type', sa.String(length=50), nullable=True, comment='失败类型: temporary, permanent, unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_services', 'failure_type')
    op.drop_column('model_services', 'last_failure_reason')
    op.drop_column('model_services', 'auto_start_retry_count')
    op.drop_column('model_services', 'priority')
    # ### end Alembic commands ###