"""remove_v1_models_and_services_tables

Revision ID: 3a6dcb6b05e3
Revises: fc1af125e519
Create Date: 2025-07-14 20:40:20.173372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6dcb6b05e3'
down_revision = 'fc1af125e519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop v1.0 tables that are no longer needed in v2.0 architecture
    op.drop_table('model_services')
    op.drop_table('model_classifications')
    op.drop_table('models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This downgrade would recreate v1.0 tables, but they're no longer supported
    # in v2.0 architecture. This is here for completeness but should not be used.
    pass
    # ### end Alembic commands ###