"""Add is_public field to models table

Revision ID: 4a3f94270aa6
Revises: ef65cb9905c8
Create Date: 2025-07-12 16:04:02.722098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3f94270aa6'
down_revision = 'ef65cb9905c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('models', sa.Column('is_public', sa.Boolean(), nullable=True))
    
    # Update existing records to set default value
    op.execute("UPDATE models SET is_public = true WHERE is_public IS NULL")
    
    # Make the column not nullable
    op.alter_column('models', 'is_public', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'is_public')
    # ### end Alembic commands ###