"""Remove example_data_path field from ModelService

Revision ID: 6f4bbc985b33
Revises: f58a456a4516
Create Date: 2025-08-10 20:37:29.936527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4bbc985b33'
down_revision = 'f58a456a4516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_services', 'example_data_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_services', sa.Column('example_data_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='示例数据路径'))
    # ### end Alembic commands ###