"""Add is_admin field to users table

Revision ID: 7c42ad2cf939
Revises: 3a6dcb6b05e3
Create Date: 2025-07-16 11:30:43.749261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c42ad2cf939'
down_revision = '3a6dcb6b05e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_admin field to users table
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, default=False))
    
    # Add last_seen_at field to users table
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    
    # Make the is_admin column non-nullable after setting defaults
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove fields from users table
    op.drop_column('users', 'last_seen_at')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###