"""add_image_unique_constraint_and_cleanup

Revision ID: b5460eaa8a63
Revises: 5504a766866f
Create Date: 2025-08-05 02:53:30.734306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5460eaa8a63'
down_revision = '5504a766866f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先清理重复的镜像记录，保留最新的
    connection = op.get_bind()
    
    # 查找并删除重复记录，保留每组中最新的记录
    connection.execute(sa.text("""
        DELETE FROM images 
        WHERE id NOT IN (
            SELECT MAX(id) 
            FROM images 
            GROUP BY name, tag, repository_id
        )
    """))
    
    # 清理失败和超时的镜像记录
    connection.execute(sa.text("""
        DELETE FROM images 
        WHERE status = 'failed' 
           OR (status IN ('uploading', 'processing') 
               AND created_at < NOW() - INTERVAL '3 days')
    """))
    
    # 添加name:tag在同一仓库中的唯一性约束
    op.create_unique_constraint(
        'uq_image_name_tag_repository', 
        'images', 
        ['name', 'tag', 'repository_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除唯一性约束
    op.drop_constraint('uq_image_name_tag_repository', 'images', type_='unique')
    # ### end Alembic commands ###