"""refactor_image_model_optimize_harbor_storage

Revision ID: d1e07f7afc09
Revises: b5460eaa8a63
Create Date: 2025-08-05 11:07:16.265939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e07f7afc09'
down_revision = 'b5460eaa8a63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 添加新字段（先设为可空）
    op.add_column('images', sa.Column('original_name', sa.String(length=255), nullable=True, comment='原始镜像名称'))
    op.add_column('images', sa.Column('original_tag', sa.String(length=100), nullable=True, comment='原始镜像标签'))
    
    # 2. 迁移现有数据
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE images SET 
            original_name = name,
            original_tag = tag
        WHERE original_name IS NULL
    """))
    
    # 3. 设置新字段为非空
    op.alter_column('images', 'original_name', nullable=False)
    op.alter_column('images', 'original_tag', nullable=False)
    
    # 4. 删除旧约束和索引
    op.drop_index(op.f('ix_images_harbor_path'), table_name='images')
    op.drop_constraint(op.f('uq_image_name_tag_repository'), 'images', type_='unique')
    
    # 5. 创建新约束
    op.create_unique_constraint('uq_image_original_name_tag_repo', 'images', ['original_name', 'original_tag', 'repository_id'])
    
    # 6. 删除旧字段
    op.drop_column('images', 'name')
    op.drop_column('images', 'harbor_project')
    op.drop_column('images', 'harbor_repository')
    op.drop_column('images', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='镜像标签'))
    op.add_column('images', sa.Column('harbor_repository', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Harbor仓库路径'))
    op.add_column('images', sa.Column('harbor_project', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Harbor项目名称'))
    op.add_column('images', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='镜像名称'))
    op.drop_constraint('uq_image_original_name_tag_repo', 'images', type_='unique')
    op.create_unique_constraint(op.f('uq_image_name_tag_repository'), 'images', ['name', 'tag', 'repository_id'])
    op.create_index(op.f('ix_images_harbor_path'), 'images', ['harbor_project', 'harbor_repository'], unique=False)
    op.drop_column('images', 'original_tag')
    op.drop_column('images', 'original_name')
    # ### end Alembic commands ###