"""Fix harbor_size field type from Integer to BigInteger

Revision ID: f58a456a4516
Revises: 33e243eebe56
Create Date: 2025-08-09 16:04:03.722707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58a456a4516'
down_revision = '33e243eebe56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'harbor_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='镜像大小(字节)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'harbor_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='镜像大小(字节)',
               existing_nullable=True)
    # ### end Alembic commands ###